In [ ]:
pip install contractions

In [ ]:
pip install unidecode

In [ ]:
pip install autocorrect

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from string import punctuation
import contractions
from unidecode import unidecode
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from autocorrect import Speller

In [ ]:
data = pd.read_csv('Train (1).csv',error_bad_lines=False, engine="python")
data.head(10)

<ipython-input-13-1efcc4cc00b9>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  data = pd.read_csv('Train (1).csv',error_bad_lines=False, engine="python")


text  label
0  I grew up (b. 1965) watching and loving the Th...      0
1  When I put this movie in my DVD player, and sa...      0
2  Why do people who do not know what a particula...      0
3  Even though I have great interest in Biblical ...      0
4  Im a die hard Dads Army fan and nothing will e...      1
5  A terrible movie as everyone has said. What ma...      0
6  Finally watched this shocking movie last night...      1
7  I caught this film on AZN on cable. It sounded...      0
8  It may be the remake of 1987 Autumn's Tale aft...      1
9  My Super Ex Girlfriend turned out to be a plea...      1

In [ ]:
data.text

0        I grew up (b. 1965) watching and loving the Th...
1        When I put this movie in my DVD player, and sa...
2        Why do people who do not know what a particula...
3        Even though I have great interest in Biblical ...
4        Im a die hard Dads Army fan and nothing will e...
                               ...                        
39995    "Western Union" is something of a forgotten cl...
39996    This movie is an incredible piece of work. It ...
39997    My wife and I watched this movie because we pl...
39998    When I first watched Flatliners, I was amazed....
39999    Why would this film be so good, but only gross...
Name: text, Length: 40000, dtype: object

In [ ]:
data.label

0        0
1        0
2        0
3        0
4        1
        ..
39995    1
39996    1
39997    0
39998    1
39999    1
Name: label, Length: 40000, dtype: int64

In [ ]:
data['text'][1]

"When I put this movie in my DVD player, and sat down with a coke and some chips, I had some expectations. I was hoping that this movie would contain some of the strong-points of the first movie: Awsome animation, good flowing story, excellent voice cast, funny comedy and a kick-ass soundtrack. But, to my disappointment, not any of this is to be found in Atlantis: Milo's Return. Had I read some reviews first, I might not have been so let down. The following paragraph will be directed to those who have seen the first movie, and who enjoyed it primarily for the points mentioned.<br /><br />When the first scene appears, your in for a shock if you just picked Atlantis: Milo's Return from the display-case at your local videoshop (or whatever), and had the expectations I had. The music feels as a bad imitation of the first movie, and the voice cast has been replaced by a not so fitting one. (With the exception of a few characters, like the voice of Sweet). The actual drawings isnt that bad, 

In [ ]:
from nltk.corpus import stopwords

In [ ]:
#1. remove spaces,newlines
def remove_spaces(data):
    clean_text = data.replace('\\n',' ').replace('\t',' ').replace('\\',' ')
    return clean_text

#2.contraction mapping
def expand_text(data):
    expanded_text = contractions.fix(data)
    return expanded_text

#3. handling accented characters
def handling_accented(data):
    fixed_text = unidecode(data)
    return fixed_text



def clean_data(data):
    tokens = word_tokenize(data)
    clean_text = [word.lower() for word in tokens if
                  (word not in punctuation) and (word.lower()
                  not in stopword_list) and (len(word)>2) and
                  (word.isalpha())]
    return clean_text

# autocorrect
def autocorrection(data):
    spell = Speller(lang='en')
    corrected_text = spell(data)
    return corrected_text

# lemmatization
def lemmatization(data):
    lemmatizer = WordNetLemmatizer()
    final_data = []
    for word in data:
        lemmatized_word = lemmatizer.lemmatize(word)
        final_data.append(lemmatized_word)
    return ' '.join(final_data)

In [ ]:
import nltk

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
#4. Cleaning
stopword_list = stopwords.words('english')
stopword_list.remove('no')
stopword_list.remove('nor')
stopword_list.remove('not')

In [ ]:
def remove_spaces(data):
    clean_text = data.replace('\\n',' ').replace('\t',' ').replace('\\',' ')
    return clean_text
remove_spaces(data['text'][1])

"When I put this movie in my DVD player, and sat down with a coke and some chips, I had some expectations. I was hoping that this movie would contain some of the strong-points of the first movie: Awsome animation, good flowing story, excellent voice cast, funny comedy and a kick-ass soundtrack. But, to my disappointment, not any of this is to be found in Atlantis: Milo's Return. Had I read some reviews first, I might not have been so let down. The following paragraph will be directed to those who have seen the first movie, and who enjoyed it primarily for the points mentioned.<br /><br />When the first scene appears, your in for a shock if you just picked Atlantis: Milo's Return from the display-case at your local videoshop (or whatever), and had the expectations I had. The music feels as a bad imitation of the first movie, and the voice cast has been replaced by a not so fitting one. (With the exception of a few characters, like the voice of Sweet). The actual drawings isnt that bad, 

In [ ]:
#  to aviod the data leakage
x_train,x_test,y_train,y_test = train_test_split(data.text,data.label,test_size=0.25,random_state=42)

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
clean_text_train = x_train.apply(remove_spaces)
clean_text_test = x_test.apply(remove_spaces)

clean_text_train = clean_text_train.apply(expand_text)
clean_text_test = clean_text_test.apply(expand_text)

clean_text_train = clean_text_train.apply(handling_accented)
clean_text_test = clean_text_test.apply(handling_accented)

clean_text_train = clean_text_train.apply(clean_data)
clean_text_test = clean_text_test.apply(clean_data)

clean_text_train = clean_text_train.apply(lemmatization)
clean_text_test = clean_text_test.apply(lemmatization)

In [ ]:
clean_text_train

26898    fifth grade language art teacher read book stu...
27635    low budget brit pop melodrama focus girl want ...
3036     well watched movie little year ago pulled dust...
5604     would almost give however confusing part well ...
36111    full length feature film world bridge found fi...
                               ...                        
6265     movie one worst movie ever seen life waste tim...
11284    movie inspiring anyone tough jam whether finan...
38158    east side story documentary musical comedy sta...
860      one boot one point doctor assistant refers wor...
15795    movie horrible lighting terrible camera moveme...
Name: text, Length: 30000, dtype: object

In [ ]:
# count vectorizer
count = CountVectorizer(max_df=0.95,max_features=1000)
count_val_train = count.fit_transform(clean_text_train)
count_val_test = count.transform(clean_text_test)


#count vecorizers out put is in the sparse matrix

In [ ]:
count_val_train
#print(count_val_train)

<30000x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 1617756 stored elements in Compressed Sparse Row format>

In [ ]:
count_val_train.A

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
count_val_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from collections import Counter

In [ ]:
#count.get_feature_names()
count.get_feature_names_out()

array(['ability', 'able', 'absolutely', 'accent', 'across', 'act',
       'acted', 'acting', 'action', 'actor', 'actress', 'actual',
       'actually', 'adaptation', 'add', 'admit', 'adult', 'adventure',
       'age', 'ago', 'agree', 'air', 'alien', 'alive', 'almost', 'alone',
       'along', 'already', 'also', 'although', 'always', 'amazing',
       'america', 'american', 'among', 'amount', 'animal', 'animation',
       'annoying', 'another', 'answer', 'anyone', 'anything', 'anyway',
       'apart', 'apparently', 'appeal', 'appear', 'appearance', 'appears',
       'appreciate', 'army', 'around', 'art', 'aside', 'ask', 'aspect',
       'atmosphere', 'attack', 'attempt', 'attention', 'audience',
       'average', 'avoid', 'award', 'away', 'awesome', 'awful', 'baby',
       'back', 'background', 'bad', 'badly', 'band', 'barely', 'based',
       'basic', 'basically', 'battle', 'beautiful', 'beauty', 'became',
       'become', 'becomes', 'begin', 'beginning', 'behind', 'belief',
       'be

In [ ]:
len(count.get_feature_names_out())

1000

In [ ]:
pd.DataFrame(count_val_train.A,columns=count.get_feature_names_out())

ability  able  absolutely  accent  across  act  acted  acting  action  \
0            0     0           0       0       0    0      0       2       0   
1            0     0           0       0       0    0      0       0       0   
2            0     0           0       0       0    0      0       0       0   
3            0     0           0       1       0    0      0       0       0   
4            0     0           2       0       0    0      0       0       0   
...        ...   ...         ...     ...     ...  ...    ...     ...     ...   
29995        0     0           0       0       0    1      0       1       0   
29996        0     0           0       0       0    0      0       0       0   
29997        0     0           0       0       0    0      0       0       0   
29998        0     0           0       0       0    0      0       1       0   
29999        0     0           0       0       0    0      0       1       0   

       actor  ...  wrong  wrote  yeah  year  yes  yet  york  young  younger  \
0          0  ...      0      0     0     0    0    0     0      0        0   
1          0  ...      0      0     0     0    0    0     0      0        0   
2          0  ...      0      0     0     1    0    0     0      0        0   
3          0  ...      0      0     0     0    0    0     0      0        0   
4          0  ...      0      0     0     0    0    0     0      0        0   
...      ...  ...    ...    ...   ...   ...  ...  ...   ...    ...      ...   
29995      0  ...      0      0     0     0    0    0     0      0        0   
29996      0  ...      0      0     0     0    0    0     0      0        0   
29997      0  ...      0      0     0     1    0    0     0      0        0   
29998      0  ...      1      0     0     0    0    0     0      0        0   
29999      0  ...      0      1     0     1    0    0     0      0        0   

       zombie  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
29995       0  
29996       0  
29997       0  
29998       0  
29999       0  

[30000 rows x 1000 columns]

In [ ]:
# build model
count_mnb = MultinomialNB()
count_mnb.fit(count_val_train.A,y_train)
predict_count = count_mnb.predict(count_val_test.A)
accuracy_count = accuracy_score(y_test,predict_count)*100
accuracy_count

83.08

In [ ]:
tfidf = TfidfVectorizer(max_df=0.95,max_features=1000)
tfidf_train = tfidf.fit_transform(clean_text_train)
tfidf_test = tfidf.transform(clean_text_test)

In [ ]:
tfidf_train.A

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
tfidf_train

<30000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1617756 stored elements in Compressed Sparse Row format>

In [ ]:
tfidf_train.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
tfidf.get_feature_names_out()

array(['ability', 'able', 'absolutely', 'accent', 'across', 'act',
       'acted', 'acting', 'action', 'actor', 'actress', 'actual',
       'actually', 'adaptation', 'add', 'admit', 'adult', 'adventure',
       'age', 'ago', 'agree', 'air', 'alien', 'alive', 'almost', 'alone',
       'along', 'already', 'also', 'although', 'always', 'amazing',
       'america', 'american', 'among', 'amount', 'animal', 'animation',
       'annoying', 'another', 'answer', 'anyone', 'anything', 'anyway',
       'apart', 'apparently', 'appeal', 'appear', 'appearance', 'appears',
       'appreciate', 'army', 'around', 'art', 'aside', 'ask', 'aspect',
       'atmosphere', 'attack', 'attempt', 'attention', 'audience',
       'average', 'avoid', 'award', 'away', 'awesome', 'awful', 'baby',
       'back', 'background', 'bad', 'badly', 'band', 'barely', 'based',
       'basic', 'basically', 'battle', 'beautiful', 'beauty', 'became',
       'become', 'becomes', 'begin', 'beginning', 'behind', 'belief',
       'be

In [ ]:
len(tfidf.get_feature_names_out())

1000

In [ ]:
pd.DataFrame(tfidf_train.A,columns=tfidf.get_feature_names_out())

ability  able  absolutely    accent  across       act  acted    acting  \
0          0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.182468   
1          0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.000000   
2          0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.000000   
3          0.0   0.0    0.000000  0.137926     0.0  0.000000    0.0  0.000000   
4          0.0   0.0    0.321531  0.000000     0.0  0.000000    0.0  0.000000   
...        ...   ...         ...       ...     ...       ...    ...       ...   
29995      0.0   0.0    0.000000  0.000000     0.0  0.135608    0.0  0.088057   
29996      0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.000000   
29997      0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.000000   
29998      0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.050570   
29999      0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.097604   

       action  actor  ...    wrong     wrote  yeah      year  yes  yet  york  \
0         0.0    0.0  ...  0.00000  0.000000   0.0  0.000000  0.0  0.0   0.0   
1         0.0    0.0  ...  0.00000  0.000000   0.0  0.000000  0.0  0.0   0.0   
2         0.0    0.0  ...  0.00000  0.000000   0.0  0.055835  0.0  0.0   0.0   
3         0.0    0.0  ...  0.00000  0.000000   0.0  0.000000  0.0  0.0   0.0   
4         0.0    0.0  ...  0.00000  0.000000   0.0  0.000000  0.0  0.0   0.0   
...       ...    ...  ...      ...       ...   ...       ...  ...  ...   ...   
29995     0.0    0.0  ...  0.00000  0.000000   0.0  0.000000  0.0  0.0   0.0   
29996     0.0    0.0  ...  0.00000  0.000000   0.0  0.000000  0.0  0.0   0.0   
29997     0.0    0.0  ...  0.00000  0.000000   0.0  0.074143  0.0  0.0   0.0   
29998     0.0    0.0  ...  0.07508  0.000000   0.0  0.000000  0.0  0.0   0.0   
29999     0.0    0.0  ...  0.00000  0.189091   0.0  0.102630  0.0  0.0   0.0   

       young  younger  zombie  
0        0.0      0.0     0.0  
1        0.0      0.0     0.0  
2        0.0      0.0     0.0  
3        0.0      0.0     0.0  
4        0.0      0.0     0.0  
...      ...      ...     ...  
29995    0.0      0.0     0.0  
29996    0.0      0.0     0.0  
29997    0.0      0.0     0.0  
29998    0.0      0.0     0.0  
29999    0.0      0.0     0.0  

[30000 rows x 1000 columns]

In [ ]:
tfidf_mnb = MultinomialNB()
tfidf_mnb.fit(tfidf_train.A,y_train)
predict_tfidf=tfidf_mnb.predict(tfidf_test.A)
accuracy_tfidf = accuracy_score(y_test,predict_tfidf)*100
accuracy_tfidf

83.67

In [ ]:
accuracy_count

83.08

In [ ]:
from nltk.util import ngrams
# [w1 w2 w3]
def splitting_dataframe(data):
    tokens = data.split()
    return tokens

data = clean_text_test.apply(splitting_dataframe)

def ngram_list(data,ngram_range):
    ngram = ngrams(data,ngram_range) # zip file
    ngram_list1 = []
    for ngram1 in ngram: #opening the zip file
        ngram_list1.append(' '.join(ngram1))
    return ngram_list1

In [ ]:
unigrams = data.apply(lambda x : ngram_list(x,1)) # x >> single review
unigrams

32823    [central, theme, movie, seems, confusion, rela...
16298    [excellent, example, cowboy, noir, called, une...
28505    [ending, made, heart, jump, throat, proceeded,...
6689     [chosen, one, appreciate, quality, story, char...
26893    [really, funny, film, especially, second, thir...
                               ...                        
29415    [film, came, gift, offering, blue, unlike, rev...
11359    [first, started, watching, movie, looking, kin...
575      [big, mark, music, neil, young, glowing, prais...
17398    [watching, lady, ermine, wondering, betty, gra...
4189     [crappy, miserably, acted, movie, based, subli...
Name: text, Length: 10000, dtype: object

In [ ]:
#bigrams = data.apply(lambda x : ngram_list1(x,2)) # x >> single review
#bigrams

In [ ]:
#bigrams = data.apply(lambda x : ngram_list1(x,2)) # x >> single review
#bigrams

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [ ]:
!kaggle datasets download -d shaunthesheep/microsoft-catsvsdogs-dataset

 99% 780M/788M [00:13<00:00, 166MB/s]
100% 788M/788M [00:13<00:00, 59.8MB/s]
